openapi: 3.0.0
info:
  title: BentleyRetailApi
  description: "An API for a online retail shop to allow users order items, track\
    \ orders, and track inventory"
  version: "0.5"
servers:
- url: https://virtserver.swaggerhub.com/holtenterprises/BrReCo/0.5
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
